name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # push:
  #   branches: # Leaving this blank causes a linter run to occur on push for all branches.
  pull_request:
    branches:
      - linter_merge

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          clang_format: true
          clang_format_auto_fix: true
          auto_fix: true
          commit: true 
          continue_on_error: false
          git_email: github.event.commits[0].author.name


