name: cpp-linter

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - linter

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          lines-change-only: true
          

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        # run: echo "Some files failed the linting checks!"
        # for actual deployment
        run: exit 1
